export { IInstantiationService, createDecorator } from './instantiation'
export { registerSingleton } from './extensions'
export { SyncDescriptor, type ServiceDescriptor } from './descriptors'
export { ServiceCollection } from './collection'
export { InstantiationService } from './service'
export type { ServicesAccessor } from './instantiation'
export type { ServiceIdentifier } from './helper/utils'
